// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentRun struct {
	ID         string             `json:"id"`
	SessionID  string             `json:"session_id"`
	Query      string             `json:"query"`
	PlanIntent string             `json:"plan_intent"`
	Trace      []byte             `json:"trace"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Asset struct {
	ID             string             `json:"id"`
	Uri            string             `json:"uri"`
	MediaType      string             `json:"media_type"`
	Sha256         string             `json:"sha256"`
	PageCount      pgtype.Int4        `json:"page_count"`
	Width          pgtype.Int4        `json:"width"`
	Height         pgtype.Int4        `json:"height"`
	SourceID       string             `json:"source_id"`
	SourceType     string             `json:"source_type"`
	SourceRecordID string             `json:"source_record_id"`
	IngestedAt     pgtype.Timestamptz `json:"ingested_at"`
}

type Attestation struct {
	ID            string             `json:"id"`
	ClaimID       string             `json:"claim_id"`
	Status        string             `json:"status"`
	ReasonCodes   []byte             `json:"reason_codes"`
	Notes         string             `json:"notes"`
	EvidenceIds   []byte             `json:"evidence_ids"`
	ValidatorType string             `json:"validator_type"`
	ValidatorID   string             `json:"validator_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Claim struct {
	ID              string             `json:"id"`
	SubjectType     string             `json:"subject_type"`
	SubjectID       string             `json:"subject_id"`
	FieldPath       string             `json:"field_path"`
	Value           []byte             `json:"value"`
	Confidence      float64            `json:"confidence"`
	Authority       string             `json:"authority"`
	SourceID        string             `json:"source_id"`
	SourceType      string             `json:"source_type"`
	SourceRecordID  string             `json:"source_record_id"`
	EvidenceIds     []byte             `json:"evidence_ids"`
	ExtractionRunID string             `json:"extraction_run_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Evidence struct {
	ID               string             `json:"id"`
	AssetID          string             `json:"asset_id"`
	Page             pgtype.Int4        `json:"page"`
	Region           []byte             `json:"region"`
	Text             string             `json:"text"`
	ImageUri         string             `json:"image_uri"`
	ContentHash      string             `json:"content_hash"`
	ExtractorName    string             `json:"extractor_name"`
	ExtractorVersion string             `json:"extractor_version"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type FitmentAssertion struct {
	ID                     string             `json:"id"`
	ProductID              string             `json:"product_id"`
	VehicleConfigurationID string             `json:"vehicle_configuration_id"`
	Compatibility          string             `json:"compatibility"`
	Conditions             []byte             `json:"conditions"`
	SourceID               string             `json:"source_id"`
	SourceType             string             `json:"source_type"`
	SourceRecordID         string             `json:"source_record_id"`
	Authority              string             `json:"authority"`
	Confidence             float64            `json:"confidence"`
	EvidenceIds            []byte             `json:"evidence_ids"`
	ObservedAt             pgtype.Timestamptz `json:"observed_at"`
	VerificationStatus     string             `json:"verification_status"`
}

type InventoryObservation struct {
	ID                 string             `json:"id"`
	ProductID          string             `json:"product_id"`
	LocationID         string             `json:"location_id"`
	Quantity           pgtype.Int4        `json:"quantity"`
	Availability       string             `json:"availability"`
	PriceAmount        pgtype.Float8      `json:"price_amount"`
	PriceCurrency      string             `json:"price_currency"`
	ObservedAt         pgtype.Timestamptz `json:"observed_at"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	Authority          string             `json:"authority"`
	Confidence         float64            `json:"confidence"`
	VerificationStatus string             `json:"verification_status"`
	SourceID           string             `json:"source_id"`
	SourceType         string             `json:"source_type"`
	SourceRecordID     string             `json:"source_record_id"`
}

type Location struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	PostalCode string  `json:"postal_code"`
	Latitude   float64 `json:"latitude"`
	Longitude  float64 `json:"longitude"`
}

type Product struct {
	ID             string             `json:"id"`
	ManufacturerID string             `json:"manufacturer_id"`
	CanonicalName  string             `json:"canonical_name"`
	Description    string             `json:"description"`
	Category       string             `json:"category"`
	Brand          string             `json:"brand"`
	Oem            bool               `json:"oem"`
	Attributes     []byte             `json:"attributes"`
	Publication    string             `json:"publication"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ProductIdentifier struct {
	ID         int64              `json:"id"`
	ProductID  string             `json:"product_id"`
	Type       string             `json:"type"`
	Value      string             `json:"value"`
	Normalized string             `json:"normalized"`
	SourceID   string             `json:"source_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ProductReview struct {
	ID            string             `json:"id"`
	ProductID     string             `json:"product_id"`
	Author        string             `json:"author"`
	Rating        int32              `json:"rating"`
	Title         string             `json:"title"`
	Content       string             `json:"content"`
	VerifiedBuyer bool               `json:"verified_buyer"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type VehicleConfiguration struct {
	ID         string `json:"id"`
	Year       int32  `json:"year"`
	Make       string `json:"make"`
	Model      string `json:"model"`
	Trim       string `json:"trim"`
	Engine     string `json:"engine"`
	Drivetrain string `json:"drivetrain"`
	BodyStyle  string `json:"body_style"`
	Attributes []byte `json:"attributes"`
}
