// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	GetAgentRun(ctx context.Context, id string) (AgentRun, error)
	GetAsset(ctx context.Context, id string) (Asset, error)
	GetAttestationForClaim(ctx context.Context, claimID string) (Attestation, error)
	GetEvidenceByID(ctx context.Context, id string) (Evidence, error)
	GetFitmentAssertion(ctx context.Context, id string) (FitmentAssertion, error)
	GetInventoryObservation(ctx context.Context, id string) (InventoryObservation, error)
	GetLocation(ctx context.Context, id string) (Location, error)
	GetProductByID(ctx context.Context, id string) (Product, error)
	GetProductByIdentifier(ctx context.Context, normalized string) (Product, error)
	GetVehicleConfig(ctx context.Context, id string) (VehicleConfiguration, error)
	InsertAgentRun(ctx context.Context, arg InsertAgentRunParams) (AgentRun, error)
	InsertClaim(ctx context.Context, arg InsertClaimParams) (Claim, error)
	InsertEvidence(ctx context.Context, arg InsertEvidenceParams) (Evidence, error)
	InsertProductIdentifier(ctx context.Context, arg InsertProductIdentifierParams) error
	InsertProductReview(ctx context.Context, arg InsertProductReviewParams) (ProductReview, error)
	ListAgentRuns(ctx context.Context, arg ListAgentRunsParams) ([]AgentRun, error)
	ListClaimsBySubject(ctx context.Context, subjectID string) ([]Claim, error)
	ListFitmentsByProduct(ctx context.Context, productID string) ([]FitmentAssertion, error)
	ListFitmentsByVehicle(ctx context.Context, vehicleConfigurationID string) ([]FitmentAssertion, error)
	ListInventoryByProduct(ctx context.Context, productID string) ([]InventoryObservation, error)
	ListProductReviews(ctx context.Context, productID string) ([]ProductReview, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	UpsertAsset(ctx context.Context, arg UpsertAssetParams) (Asset, error)
	UpsertAttestation(ctx context.Context, arg UpsertAttestationParams) (Attestation, error)
	UpsertFitmentAssertion(ctx context.Context, arg UpsertFitmentAssertionParams) (FitmentAssertion, error)
	UpsertInventoryObservation(ctx context.Context, arg UpsertInventoryObservationParams) (InventoryObservation, error)
	UpsertLocation(ctx context.Context, arg UpsertLocationParams) (Location, error)
	UpsertProduct(ctx context.Context, arg UpsertProductParams) (Product, error)
	UpsertVehicleConfig(ctx context.Context, arg UpsertVehicleConfigParams) (VehicleConfiguration, error)
}

var _ Querier = (*Queries)(nil)
