// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAgentRun = `-- name: GetAgentRun :one
SELECT id, session_id, query, plan_intent, trace, status, created_at FROM agent_runs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAgentRun(ctx context.Context, id string) (AgentRun, error) {
	row := q.db.QueryRow(ctx, getAgentRun, id)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Query,
		&i.PlanIntent,
		&i.Trace,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, uri, media_type, sha256, page_count, width, height, source_id, source_type, source_record_id, ingested_at FROM assets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAsset(ctx context.Context, id string) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Uri,
		&i.MediaType,
		&i.Sha256,
		&i.PageCount,
		&i.Width,
		&i.Height,
		&i.SourceID,
		&i.SourceType,
		&i.SourceRecordID,
		&i.IngestedAt,
	)
	return i, err
}

const getAttestationForClaim = `-- name: GetAttestationForClaim :one
SELECT id, claim_id, status, reason_codes, notes, evidence_ids, validator_type, validator_id, created_at FROM attestations
WHERE claim_id = $1 LIMIT 1
`

func (q *Queries) GetAttestationForClaim(ctx context.Context, claimID string) (Attestation, error) {
	row := q.db.QueryRow(ctx, getAttestationForClaim, claimID)
	var i Attestation
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.Status,
		&i.ReasonCodes,
		&i.Notes,
		&i.EvidenceIds,
		&i.ValidatorType,
		&i.ValidatorID,
		&i.CreatedAt,
	)
	return i, err
}

const getEvidenceByID = `-- name: GetEvidenceByID :one
SELECT id, asset_id, page, region, text, image_uri, content_hash, extractor_name, extractor_version, created_at FROM evidence
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEvidenceByID(ctx context.Context, id string) (Evidence, error) {
	row := q.db.QueryRow(ctx, getEvidenceByID, id)
	var i Evidence
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Page,
		&i.Region,
		&i.Text,
		&i.ImageUri,
		&i.ContentHash,
		&i.ExtractorName,
		&i.ExtractorVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getFitmentAssertion = `-- name: GetFitmentAssertion :one
SELECT id, product_id, vehicle_configuration_id, compatibility, conditions, source_id, source_type, source_record_id, authority, confidence, evidence_ids, observed_at, verification_status FROM fitment_assertions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFitmentAssertion(ctx context.Context, id string) (FitmentAssertion, error) {
	row := q.db.QueryRow(ctx, getFitmentAssertion, id)
	var i FitmentAssertion
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VehicleConfigurationID,
		&i.Compatibility,
		&i.Conditions,
		&i.SourceID,
		&i.SourceType,
		&i.SourceRecordID,
		&i.Authority,
		&i.Confidence,
		&i.EvidenceIds,
		&i.ObservedAt,
		&i.VerificationStatus,
	)
	return i, err
}

const getInventoryObservation = `-- name: GetInventoryObservation :one
SELECT id, product_id, location_id, quantity, availability, price_amount, price_currency, observed_at, received_at, expires_at, authority, confidence, verification_status, source_id, source_type, source_record_id FROM inventory_observations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInventoryObservation(ctx context.Context, id string) (InventoryObservation, error) {
	row := q.db.QueryRow(ctx, getInventoryObservation, id)
	var i InventoryObservation
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.LocationID,
		&i.Quantity,
		&i.Availability,
		&i.PriceAmount,
		&i.PriceCurrency,
		&i.ObservedAt,
		&i.ReceivedAt,
		&i.ExpiresAt,
		&i.Authority,
		&i.Confidence,
		&i.VerificationStatus,
		&i.SourceID,
		&i.SourceType,
		&i.SourceRecordID,
	)
	return i, err
}

const getLocation = `-- name: GetLocation :one
SELECT id, name, postal_code, latitude, longitude FROM locations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLocation(ctx context.Context, id string) (Location, error) {
	row := q.db.QueryRow(ctx, getLocation, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, manufacturer_id, canonical_name, description, category, brand, oem, attributes, publication, created_at, updated_at FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ManufacturerID,
		&i.CanonicalName,
		&i.Description,
		&i.Category,
		&i.Brand,
		&i.Oem,
		&i.Attributes,
		&i.Publication,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByIdentifier = `-- name: GetProductByIdentifier :one
SELECT p.id, p.manufacturer_id, p.canonical_name, p.description, p.category, p.brand, p.oem, p.attributes, p.publication, p.created_at, p.updated_at FROM products p
JOIN product_identifiers pi ON p.id = pi.product_id
WHERE pi.normalized = $1 LIMIT 1
`

func (q *Queries) GetProductByIdentifier(ctx context.Context, normalized string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByIdentifier, normalized)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ManufacturerID,
		&i.CanonicalName,
		&i.Description,
		&i.Category,
		&i.Brand,
		&i.Oem,
		&i.Attributes,
		&i.Publication,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVehicleConfig = `-- name: GetVehicleConfig :one
SELECT id, year, make, model, trim, engine, drivetrain, body_style, attributes FROM vehicle_configurations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetVehicleConfig(ctx context.Context, id string) (VehicleConfiguration, error) {
	row := q.db.QueryRow(ctx, getVehicleConfig, id)
	var i VehicleConfiguration
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Make,
		&i.Model,
		&i.Trim,
		&i.Engine,
		&i.Drivetrain,
		&i.BodyStyle,
		&i.Attributes,
	)
	return i, err
}

const insertAgentRun = `-- name: InsertAgentRun :one
INSERT INTO agent_runs (
    id, session_id, query, plan_intent, trace, status, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, session_id, query, plan_intent, trace, status, created_at
`

type InsertAgentRunParams struct {
	ID         string             `json:"id"`
	SessionID  string             `json:"session_id"`
	Query      string             `json:"query"`
	PlanIntent string             `json:"plan_intent"`
	Trace      []byte             `json:"trace"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertAgentRun(ctx context.Context, arg InsertAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, insertAgentRun,
		arg.ID,
		arg.SessionID,
		arg.Query,
		arg.PlanIntent,
		arg.Trace,
		arg.Status,
		arg.CreatedAt,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Query,
		&i.PlanIntent,
		&i.Trace,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertClaim = `-- name: InsertClaim :one
INSERT INTO claims (
    id, subject_type, subject_id, field_path, value, confidence, authority, source_id, source_type, source_record_id, evidence_ids, extraction_run_id, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, subject_type, subject_id, field_path, value, confidence, authority, source_id, source_type, source_record_id, evidence_ids, extraction_run_id, created_at
`

type InsertClaimParams struct {
	ID              string             `json:"id"`
	SubjectType     string             `json:"subject_type"`
	SubjectID       string             `json:"subject_id"`
	FieldPath       string             `json:"field_path"`
	Value           []byte             `json:"value"`
	Confidence      float64            `json:"confidence"`
	Authority       string             `json:"authority"`
	SourceID        string             `json:"source_id"`
	SourceType      string             `json:"source_type"`
	SourceRecordID  string             `json:"source_record_id"`
	EvidenceIds     []byte             `json:"evidence_ids"`
	ExtractionRunID string             `json:"extraction_run_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertClaim(ctx context.Context, arg InsertClaimParams) (Claim, error) {
	row := q.db.QueryRow(ctx, insertClaim,
		arg.ID,
		arg.SubjectType,
		arg.SubjectID,
		arg.FieldPath,
		arg.Value,
		arg.Confidence,
		arg.Authority,
		arg.SourceID,
		arg.SourceType,
		arg.SourceRecordID,
		arg.EvidenceIds,
		arg.ExtractionRunID,
		arg.CreatedAt,
	)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectID,
		&i.FieldPath,
		&i.Value,
		&i.Confidence,
		&i.Authority,
		&i.SourceID,
		&i.SourceType,
		&i.SourceRecordID,
		&i.EvidenceIds,
		&i.ExtractionRunID,
		&i.CreatedAt,
	)
	return i, err
}

const insertEvidence = `-- name: InsertEvidence :one
INSERT INTO evidence (
    id, asset_id, page, region, text, image_uri, content_hash, extractor_name, extractor_version, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, asset_id, page, region, text, image_uri, content_hash, extractor_name, extractor_version, created_at
`

type InsertEvidenceParams struct {
	ID               string             `json:"id"`
	AssetID          string             `json:"asset_id"`
	Page             pgtype.Int4        `json:"page"`
	Region           []byte             `json:"region"`
	Text             string             `json:"text"`
	ImageUri         string             `json:"image_uri"`
	ContentHash      string             `json:"content_hash"`
	ExtractorName    string             `json:"extractor_name"`
	ExtractorVersion string             `json:"extractor_version"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertEvidence(ctx context.Context, arg InsertEvidenceParams) (Evidence, error) {
	row := q.db.QueryRow(ctx, insertEvidence,
		arg.ID,
		arg.AssetID,
		arg.Page,
		arg.Region,
		arg.Text,
		arg.ImageUri,
		arg.ContentHash,
		arg.ExtractorName,
		arg.ExtractorVersion,
		arg.CreatedAt,
	)
	var i Evidence
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Page,
		&i.Region,
		&i.Text,
		&i.ImageUri,
		&i.ContentHash,
		&i.ExtractorName,
		&i.ExtractorVersion,
		&i.CreatedAt,
	)
	return i, err
}

const insertProductIdentifier = `-- name: InsertProductIdentifier :exec
INSERT INTO product_identifiers (
    product_id, type, value, normalized, source_id
) VALUES (
    $1, $2, $3, $4, $5
)
`

type InsertProductIdentifierParams struct {
	ProductID  string `json:"product_id"`
	Type       string `json:"type"`
	Value      string `json:"value"`
	Normalized string `json:"normalized"`
	SourceID   string `json:"source_id"`
}

func (q *Queries) InsertProductIdentifier(ctx context.Context, arg InsertProductIdentifierParams) error {
	_, err := q.db.Exec(ctx, insertProductIdentifier,
		arg.ProductID,
		arg.Type,
		arg.Value,
		arg.Normalized,
		arg.SourceID,
	)
	return err
}

const insertProductReview = `-- name: InsertProductReview :one
INSERT INTO product_reviews (
    id, product_id, author, rating, title, content, verified_buyer, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, product_id, author, rating, title, content, verified_buyer, created_at
`

type InsertProductReviewParams struct {
	ID            string             `json:"id"`
	ProductID     string             `json:"product_id"`
	Author        string             `json:"author"`
	Rating        int32              `json:"rating"`
	Title         string             `json:"title"`
	Content       string             `json:"content"`
	VerifiedBuyer bool               `json:"verified_buyer"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertProductReview(ctx context.Context, arg InsertProductReviewParams) (ProductReview, error) {
	row := q.db.QueryRow(ctx, insertProductReview,
		arg.ID,
		arg.ProductID,
		arg.Author,
		arg.Rating,
		arg.Title,
		arg.Content,
		arg.VerifiedBuyer,
		arg.CreatedAt,
	)
	var i ProductReview
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Author,
		&i.Rating,
		&i.Title,
		&i.Content,
		&i.VerifiedBuyer,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentRuns = `-- name: ListAgentRuns :many
SELECT id, session_id, query, plan_intent, trace, status, created_at FROM agent_runs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAgentRunsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAgentRuns(ctx context.Context, arg ListAgentRunsParams) ([]AgentRun, error) {
	rows, err := q.db.Query(ctx, listAgentRuns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentRun
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Query,
			&i.PlanIntent,
			&i.Trace,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimsBySubject = `-- name: ListClaimsBySubject :many
SELECT id, subject_type, subject_id, field_path, value, confidence, authority, source_id, source_type, source_record_id, evidence_ids, extraction_run_id, created_at FROM claims
WHERE subject_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListClaimsBySubject(ctx context.Context, subjectID string) ([]Claim, error) {
	rows, err := q.db.Query(ctx, listClaimsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Claim
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.SubjectID,
			&i.FieldPath,
			&i.Value,
			&i.Confidence,
			&i.Authority,
			&i.SourceID,
			&i.SourceType,
			&i.SourceRecordID,
			&i.EvidenceIds,
			&i.ExtractionRunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFitmentsByProduct = `-- name: ListFitmentsByProduct :many
SELECT id, product_id, vehicle_configuration_id, compatibility, conditions, source_id, source_type, source_record_id, authority, confidence, evidence_ids, observed_at, verification_status FROM fitment_assertions
WHERE product_id = $1
ORDER BY observed_at DESC
`

func (q *Queries) ListFitmentsByProduct(ctx context.Context, productID string) ([]FitmentAssertion, error) {
	rows, err := q.db.Query(ctx, listFitmentsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FitmentAssertion
	for rows.Next() {
		var i FitmentAssertion
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.VehicleConfigurationID,
			&i.Compatibility,
			&i.Conditions,
			&i.SourceID,
			&i.SourceType,
			&i.SourceRecordID,
			&i.Authority,
			&i.Confidence,
			&i.EvidenceIds,
			&i.ObservedAt,
			&i.VerificationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFitmentsByVehicle = `-- name: ListFitmentsByVehicle :many
SELECT id, product_id, vehicle_configuration_id, compatibility, conditions, source_id, source_type, source_record_id, authority, confidence, evidence_ids, observed_at, verification_status FROM fitment_assertions
WHERE vehicle_configuration_id = $1
ORDER BY observed_at DESC
`

func (q *Queries) ListFitmentsByVehicle(ctx context.Context, vehicleConfigurationID string) ([]FitmentAssertion, error) {
	rows, err := q.db.Query(ctx, listFitmentsByVehicle, vehicleConfigurationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FitmentAssertion
	for rows.Next() {
		var i FitmentAssertion
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.VehicleConfigurationID,
			&i.Compatibility,
			&i.Conditions,
			&i.SourceID,
			&i.SourceType,
			&i.SourceRecordID,
			&i.Authority,
			&i.Confidence,
			&i.EvidenceIds,
			&i.ObservedAt,
			&i.VerificationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryByProduct = `-- name: ListInventoryByProduct :many
SELECT id, product_id, location_id, quantity, availability, price_amount, price_currency, observed_at, received_at, expires_at, authority, confidence, verification_status, source_id, source_type, source_record_id FROM inventory_observations
WHERE product_id = $1
ORDER BY observed_at DESC
`

func (q *Queries) ListInventoryByProduct(ctx context.Context, productID string) ([]InventoryObservation, error) {
	rows, err := q.db.Query(ctx, listInventoryByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryObservation
	for rows.Next() {
		var i InventoryObservation
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.LocationID,
			&i.Quantity,
			&i.Availability,
			&i.PriceAmount,
			&i.PriceCurrency,
			&i.ObservedAt,
			&i.ReceivedAt,
			&i.ExpiresAt,
			&i.Authority,
			&i.Confidence,
			&i.VerificationStatus,
			&i.SourceID,
			&i.SourceType,
			&i.SourceRecordID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductReviews = `-- name: ListProductReviews :many
SELECT id, product_id, author, rating, title, content, verified_buyer, created_at FROM product_reviews
WHERE product_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProductReviews(ctx context.Context, productID string) ([]ProductReview, error) {
	rows, err := q.db.Query(ctx, listProductReviews, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductReview
	for rows.Next() {
		var i ProductReview
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Author,
			&i.Rating,
			&i.Title,
			&i.Content,
			&i.VerifiedBuyer,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, manufacturer_id, canonical_name, description, category, brand, oem, attributes, publication, created_at, updated_at FROM products
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ManufacturerID,
			&i.CanonicalName,
			&i.Description,
			&i.Category,
			&i.Brand,
			&i.Oem,
			&i.Attributes,
			&i.Publication,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAsset = `-- name: UpsertAsset :one
INSERT INTO assets (
    id, uri, media_type, sha256, page_count, width, height, source_id, source_type, source_record_id, ingested_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (id) DO UPDATE SET
    uri = EXCLUDED.uri,
    media_type = EXCLUDED.media_type,
    sha256 = EXCLUDED.sha256,
    page_count = EXCLUDED.page_count,
    width = EXCLUDED.width,
    height = EXCLUDED.height
RETURNING id, uri, media_type, sha256, page_count, width, height, source_id, source_type, source_record_id, ingested_at
`

type UpsertAssetParams struct {
	ID             string             `json:"id"`
	Uri            string             `json:"uri"`
	MediaType      string             `json:"media_type"`
	Sha256         string             `json:"sha256"`
	PageCount      pgtype.Int4        `json:"page_count"`
	Width          pgtype.Int4        `json:"width"`
	Height         pgtype.Int4        `json:"height"`
	SourceID       string             `json:"source_id"`
	SourceType     string             `json:"source_type"`
	SourceRecordID string             `json:"source_record_id"`
	IngestedAt     pgtype.Timestamptz `json:"ingested_at"`
}

func (q *Queries) UpsertAsset(ctx context.Context, arg UpsertAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, upsertAsset,
		arg.ID,
		arg.Uri,
		arg.MediaType,
		arg.Sha256,
		arg.PageCount,
		arg.Width,
		arg.Height,
		arg.SourceID,
		arg.SourceType,
		arg.SourceRecordID,
		arg.IngestedAt,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Uri,
		&i.MediaType,
		&i.Sha256,
		&i.PageCount,
		&i.Width,
		&i.Height,
		&i.SourceID,
		&i.SourceType,
		&i.SourceRecordID,
		&i.IngestedAt,
	)
	return i, err
}

const upsertAttestation = `-- name: UpsertAttestation :one
INSERT INTO attestations (
    id, claim_id, status, reason_codes, notes, evidence_ids, validator_type, validator_id, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status,
    reason_codes = EXCLUDED.reason_codes,
    notes = EXCLUDED.notes,
    evidence_ids = EXCLUDED.evidence_ids,
    validator_type = EXCLUDED.validator_type,
    validator_id = EXCLUDED.validator_id
RETURNING id, claim_id, status, reason_codes, notes, evidence_ids, validator_type, validator_id, created_at
`

type UpsertAttestationParams struct {
	ID            string             `json:"id"`
	ClaimID       string             `json:"claim_id"`
	Status        string             `json:"status"`
	ReasonCodes   []byte             `json:"reason_codes"`
	Notes         string             `json:"notes"`
	EvidenceIds   []byte             `json:"evidence_ids"`
	ValidatorType string             `json:"validator_type"`
	ValidatorID   string             `json:"validator_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertAttestation(ctx context.Context, arg UpsertAttestationParams) (Attestation, error) {
	row := q.db.QueryRow(ctx, upsertAttestation,
		arg.ID,
		arg.ClaimID,
		arg.Status,
		arg.ReasonCodes,
		arg.Notes,
		arg.EvidenceIds,
		arg.ValidatorType,
		arg.ValidatorID,
		arg.CreatedAt,
	)
	var i Attestation
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.Status,
		&i.ReasonCodes,
		&i.Notes,
		&i.EvidenceIds,
		&i.ValidatorType,
		&i.ValidatorID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertFitmentAssertion = `-- name: UpsertFitmentAssertion :one
INSERT INTO fitment_assertions (
    id, product_id, vehicle_configuration_id, compatibility, conditions, source_id, source_type, source_record_id, authority, confidence, evidence_ids, observed_at, verification_status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (id) DO UPDATE SET
    compatibility = EXCLUDED.compatibility,
    conditions = EXCLUDED.conditions,
    authority = EXCLUDED.authority,
    confidence = EXCLUDED.confidence,
    evidence_ids = EXCLUDED.evidence_ids,
    observed_at = EXCLUDED.observed_at,
    verification_status = EXCLUDED.verification_status
RETURNING id, product_id, vehicle_configuration_id, compatibility, conditions, source_id, source_type, source_record_id, authority, confidence, evidence_ids, observed_at, verification_status
`

type UpsertFitmentAssertionParams struct {
	ID                     string             `json:"id"`
	ProductID              string             `json:"product_id"`
	VehicleConfigurationID string             `json:"vehicle_configuration_id"`
	Compatibility          string             `json:"compatibility"`
	Conditions             []byte             `json:"conditions"`
	SourceID               string             `json:"source_id"`
	SourceType             string             `json:"source_type"`
	SourceRecordID         string             `json:"source_record_id"`
	Authority              string             `json:"authority"`
	Confidence             float64            `json:"confidence"`
	EvidenceIds            []byte             `json:"evidence_ids"`
	ObservedAt             pgtype.Timestamptz `json:"observed_at"`
	VerificationStatus     string             `json:"verification_status"`
}

func (q *Queries) UpsertFitmentAssertion(ctx context.Context, arg UpsertFitmentAssertionParams) (FitmentAssertion, error) {
	row := q.db.QueryRow(ctx, upsertFitmentAssertion,
		arg.ID,
		arg.ProductID,
		arg.VehicleConfigurationID,
		arg.Compatibility,
		arg.Conditions,
		arg.SourceID,
		arg.SourceType,
		arg.SourceRecordID,
		arg.Authority,
		arg.Confidence,
		arg.EvidenceIds,
		arg.ObservedAt,
		arg.VerificationStatus,
	)
	var i FitmentAssertion
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VehicleConfigurationID,
		&i.Compatibility,
		&i.Conditions,
		&i.SourceID,
		&i.SourceType,
		&i.SourceRecordID,
		&i.Authority,
		&i.Confidence,
		&i.EvidenceIds,
		&i.ObservedAt,
		&i.VerificationStatus,
	)
	return i, err
}

const upsertInventoryObservation = `-- name: UpsertInventoryObservation :one
INSERT INTO inventory_observations (
    id, product_id, location_id, quantity, availability, price_amount, price_currency, observed_at, received_at, expires_at, authority, confidence, verification_status, source_id, source_type, source_record_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
ON CONFLICT (id) DO UPDATE SET
    quantity = EXCLUDED.quantity,
    availability = EXCLUDED.availability,
    price_amount = EXCLUDED.price_amount,
    price_currency = EXCLUDED.price_currency,
    observed_at = EXCLUDED.observed_at,
    received_at = EXCLUDED.received_at,
    expires_at = EXCLUDED.expires_at,
    authority = EXCLUDED.authority,
    confidence = EXCLUDED.confidence,
    verification_status = EXCLUDED.verification_status
RETURNING id, product_id, location_id, quantity, availability, price_amount, price_currency, observed_at, received_at, expires_at, authority, confidence, verification_status, source_id, source_type, source_record_id
`

type UpsertInventoryObservationParams struct {
	ID                 string             `json:"id"`
	ProductID          string             `json:"product_id"`
	LocationID         string             `json:"location_id"`
	Quantity           pgtype.Int4        `json:"quantity"`
	Availability       string             `json:"availability"`
	PriceAmount        pgtype.Float8      `json:"price_amount"`
	PriceCurrency      string             `json:"price_currency"`
	ObservedAt         pgtype.Timestamptz `json:"observed_at"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	Authority          string             `json:"authority"`
	Confidence         float64            `json:"confidence"`
	VerificationStatus string             `json:"verification_status"`
	SourceID           string             `json:"source_id"`
	SourceType         string             `json:"source_type"`
	SourceRecordID     string             `json:"source_record_id"`
}

func (q *Queries) UpsertInventoryObservation(ctx context.Context, arg UpsertInventoryObservationParams) (InventoryObservation, error) {
	row := q.db.QueryRow(ctx, upsertInventoryObservation,
		arg.ID,
		arg.ProductID,
		arg.LocationID,
		arg.Quantity,
		arg.Availability,
		arg.PriceAmount,
		arg.PriceCurrency,
		arg.ObservedAt,
		arg.ReceivedAt,
		arg.ExpiresAt,
		arg.Authority,
		arg.Confidence,
		arg.VerificationStatus,
		arg.SourceID,
		arg.SourceType,
		arg.SourceRecordID,
	)
	var i InventoryObservation
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.LocationID,
		&i.Quantity,
		&i.Availability,
		&i.PriceAmount,
		&i.PriceCurrency,
		&i.ObservedAt,
		&i.ReceivedAt,
		&i.ExpiresAt,
		&i.Authority,
		&i.Confidence,
		&i.VerificationStatus,
		&i.SourceID,
		&i.SourceType,
		&i.SourceRecordID,
	)
	return i, err
}

const upsertLocation = `-- name: UpsertLocation :one
INSERT INTO locations (
    id, name, postal_code, latitude, longitude
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    postal_code = EXCLUDED.postal_code,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude
RETURNING id, name, postal_code, latitude, longitude
`

type UpsertLocationParams struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	PostalCode string  `json:"postal_code"`
	Latitude   float64 `json:"latitude"`
	Longitude  float64 `json:"longitude"`
}

func (q *Queries) UpsertLocation(ctx context.Context, arg UpsertLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, upsertLocation,
		arg.ID,
		arg.Name,
		arg.PostalCode,
		arg.Latitude,
		arg.Longitude,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const upsertProduct = `-- name: UpsertProduct :one
INSERT INTO products (
    id, manufacturer_id, canonical_name, description, category, brand, oem, attributes, publication, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW()
)
ON CONFLICT (id) DO UPDATE SET
    manufacturer_id = EXCLUDED.manufacturer_id,
    canonical_name = EXCLUDED.canonical_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    brand = EXCLUDED.brand,
    oem = EXCLUDED.oem,
    attributes = EXCLUDED.attributes,
    publication = EXCLUDED.publication,
    updated_at = NOW()
RETURNING id, manufacturer_id, canonical_name, description, category, brand, oem, attributes, publication, created_at, updated_at
`

type UpsertProductParams struct {
	ID             string `json:"id"`
	ManufacturerID string `json:"manufacturer_id"`
	CanonicalName  string `json:"canonical_name"`
	Description    string `json:"description"`
	Category       string `json:"category"`
	Brand          string `json:"brand"`
	Oem            bool   `json:"oem"`
	Attributes     []byte `json:"attributes"`
	Publication    string `json:"publication"`
}

func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, upsertProduct,
		arg.ID,
		arg.ManufacturerID,
		arg.CanonicalName,
		arg.Description,
		arg.Category,
		arg.Brand,
		arg.Oem,
		arg.Attributes,
		arg.Publication,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ManufacturerID,
		&i.CanonicalName,
		&i.Description,
		&i.Category,
		&i.Brand,
		&i.Oem,
		&i.Attributes,
		&i.Publication,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertVehicleConfig = `-- name: UpsertVehicleConfig :one
INSERT INTO vehicle_configurations (
    id, year, make, model, trim, engine, drivetrain, body_style, attributes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (id) DO UPDATE SET
    year = EXCLUDED.year,
    make = EXCLUDED.make,
    model = EXCLUDED.model,
    trim = EXCLUDED.trim,
    engine = EXCLUDED.engine,
    drivetrain = EXCLUDED.drivetrain,
    body_style = EXCLUDED.body_style,
    attributes = EXCLUDED.attributes
RETURNING id, year, make, model, trim, engine, drivetrain, body_style, attributes
`

type UpsertVehicleConfigParams struct {
	ID         string `json:"id"`
	Year       int32  `json:"year"`
	Make       string `json:"make"`
	Model      string `json:"model"`
	Trim       string `json:"trim"`
	Engine     string `json:"engine"`
	Drivetrain string `json:"drivetrain"`
	BodyStyle  string `json:"body_style"`
	Attributes []byte `json:"attributes"`
}

func (q *Queries) UpsertVehicleConfig(ctx context.Context, arg UpsertVehicleConfigParams) (VehicleConfiguration, error) {
	row := q.db.QueryRow(ctx, upsertVehicleConfig,
		arg.ID,
		arg.Year,
		arg.Make,
		arg.Model,
		arg.Trim,
		arg.Engine,
		arg.Drivetrain,
		arg.BodyStyle,
		arg.Attributes,
	)
	var i VehicleConfiguration
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Make,
		&i.Model,
		&i.Trim,
		&i.Engine,
		&i.Drivetrain,
		&i.BodyStyle,
		&i.Attributes,
	)
	return i, err
}
